name: 'ryagent_warehouse'
version: '1.0.0'
config-version: 2

profile: 'ryagent_warehouse'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  ryagent_warehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  primary_team_member_name: 'Ryan Owens'
